# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38bc169ba6f2c90a09e93a99c43c71afcccb5f1321baa6652de987e2e7b97eff9c28cbd82a281288d6a4c3c7ee6e6d9adebc8a200cab1b0487ffe8c7219b1d95

test:
  secret_key_base: e8f1a49c656b3b57244628cb06542031a07934c154aa207df11faae532674e2a433ca6cc9a96cb80ec389d90bee033ec1c9f71f5769135647ac0f2a7a9e6b441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
